# Generated by Django 3.2.21 on 2023-11-09 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=50)),
                ('essencial', models.BooleanField(default=False)),
                ('valor_planejamento', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apelido', models.CharField(max_length=50)),
                ('banco', models.CharField(choices=[('NU', 'Nubank'), ('CE', 'Caixa econômica'), ('BB', 'Banco do Brasil'), ('BR', 'Bradesco'), ('SA', 'Santander'), ('XP', 'XP Investimentos'), ('BTG', 'BTG Pactual'), ('C6', 'C6 Bank'), ('Inter', 'Inter'), ('PagBank', 'PagSeguro')], max_length=10)),
                ('tipo', models.CharField(choices=[('pf', 'Pessoa física'), ('pj', 'Pessoa jurídica')], max_length=2)),
                ('valor', models.FloatField()),
                ('icone', models.ImageField(upload_to='icones')),
                ('excluido', models.BooleanField(default=False)),
            ],
        ),
    ]
